apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  storageClassName: manual 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /root/mysql
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wp-claim
  labels:
    name: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: db-volume
  storageClassName: manual
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpressdb-deploy
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: wordpressdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: wordpressdb
    spec:
      containers:
      - image: mysql
        name: wordpressdb-container
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: wordpressdb-svc
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-wp-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpressdb-svc
  labels:
    app: wordpress
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress
    tier: wordpressdb
  clusterIP: None
